config/routes.rb
Rails.application.routes.draw do
  resources :bank_subsidiaries
  resources :banks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank.rb
class Bank < ApplicationRecord
  has_many :bank_subsidiaries, dependent: :destroy
  accepts_nested_attributes_for :bank_subsidiaries, reject_if: proc { |attr| attr['address'].blank? }, allow_destroy: true
  validates :name, presence: true

  def to_s
    name
  end
end

app/models/bank_subsidiary.rb
class BankSubsidiary < ApplicationRecord
  belongs_to :bank
  validates :address, presence: true

  def to_s
    address
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_subsidiaries_controller.rb
class BankSubsidiariesController < ApplicationController
  before_action :set_bank_subsidiary, only: %i[ show edit update destroy ]

  # GET /bank_subsidiaries or /bank_subsidiaries.json
  def index
    @bank_subsidiaries = BankSubsidiary.all
  end

  # GET /bank_subsidiaries/1 or /bank_subsidiaries/1.json
  def show
  end

  # GET /bank_subsidiaries/new
  def new
    @bank_subsidiary = BankSubsidiary.new
  end

  # GET /bank_subsidiaries/1/edit
  def edit
  end

  # POST /bank_subsidiaries or /bank_subsidiaries.json
  def create
    @bank_subsidiary = BankSubsidiary.new(bank_subsidiary_params)

    respond_to do |format|
      if @bank_subsidiary.save
        format.html { redirect_to bank_subsidiary_url(@bank_subsidiary), notice: "Bank subsidiary was successfully created." }
        format.json { render :show, status: :created, location: @bank_subsidiary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank_subsidiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_subsidiaries/1 or /bank_subsidiaries/1.json
  def update
    respond_to do |format|
      if @bank_subsidiary.update(bank_subsidiary_params)
        format.html { redirect_to bank_subsidiary_url(@bank_subsidiary), notice: "Bank subsidiary was successfully updated." }
        format.json { render :show, status: :ok, location: @bank_subsidiary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank_subsidiary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_subsidiaries/1 or /bank_subsidiaries/1.json
  def destroy
    @bank_subsidiary.destroy

    respond_to do |format|
      format.html { redirect_to bank_subsidiaries_url, notice: "Bank subsidiary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_subsidiary
      @bank_subsidiary = BankSubsidiary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_subsidiary_params
      params.require(:bank_subsidiary).permit(:address, :bank_id)
    end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: %i[ show edit update destroy ]

  # GET /banks or /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1 or /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
    @bank.bank_subsidiaries.build
  end

  # GET /banks/1/edit
  def edit
    @bank.bank_subsidiaries.build
  end

  # POST /banks or /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully created." }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1 or /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to bank_url(@bank), notice: "Bank was successfully updated." }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1 or /banks/1.json
  def destroy
    @bank.destroy

    respond_to do |format|
      format.html { redirect_to banks_url, notice: "Bank was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_params
      params.require(:bank).permit(:name, bank_subsidiaries_attributes: [:id, :address, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_subsidiaries_helper.rb
module BankSubsidiariesHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/bank_subsidiaries/_bank_subsidiary.html.erb
<div id="<%= dom_id bank_subsidiary %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= bank_subsidiary.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Bank:</strong>
    <%= bank_subsidiary.bank_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this bank subsidiary", bank_subsidiary, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this bank subsidiary', edit_bank_subsidiary_path(bank_subsidiary), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/bank_subsidiaries/_form.html.erb
<%= form_with(model: bank_subsidiary, class: "contents") do |form| %>
  <% if bank_subsidiary.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bank_subsidiary.errors.count, "error") %> prohibited this bank_subsidiary from being saved:</h2>

      <ul>
        <% bank_subsidiary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bank_id %>
    <%= form.text_field :bank_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/bank_subsidiaries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bank subsidiary</h1>

  <%= render "form", bank_subsidiary: @bank_subsidiary %>

  <%= link_to "Show this bank subsidiary", @bank_subsidiary, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to bank subsidiaries", bank_subsidiaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bank_subsidiaries/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Bank subsidiaries</h1>
    <%= link_to 'New bank subsidiary', new_bank_subsidiary_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="bank_subsidiaries" class="min-w-full">
    <%= render @bank_subsidiaries %>
  </div>
</div>

app/views/bank_subsidiaries/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New bank subsidiary</h1>

  <%= render "form", bank_subsidiary: @bank_subsidiary %>

  <%= link_to 'Back to bank subsidiaries', bank_subsidiaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bank_subsidiaries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bank_subsidiary %>

    <%= link_to 'Edit this bank_subsidiary', edit_bank_subsidiary_path(@bank_subsidiary), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this bank_subsidiary', bank_subsidiary_path(@bank_subsidiary), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to bank_subsidiaries', bank_subsidiaries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/banks/_bank.html.erb
<div id="<%= dom_id bank %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= bank.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this bank", bank, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this bank', edit_bank_path(bank), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/banks/_form.html.erb
<%= form_with(model: bank, class: "contents") do |form| %>
  <% if bank.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
        <% bank.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <h2>Sucursales</h2>


  <%= form.fields_for :bank_subsidiaries do | subsidiary | %>
    <div class="bank_subsidiaries_fields my-5">
      <div class="fields">
        <%= subsidiary.label :address, "Direccion" %><br>
        <%= subsidiary.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        <%= subsidiary.check_box :_destroy %>
        <%= subsidiary.label :_destroy, "Borrar" %>
      </div>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bank</h1>

  <%= render "form", bank: @bank %>

  <%= link_to "Show this bank", @bank, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to banks", banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/banks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Banks</h1>
    <%= link_to 'New bank', new_bank_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="banks" class="min-w-full">
    <%= render @banks %>
  </div>
</div>

app/views/banks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New bank</h1>

  <%= render "form", bank: @bank %>

  <%= link_to 'Back to banks', banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/banks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bank %>

    <h2>Sucursales</h2>

    <% if @bank.bank_subsidiaries.any? %>
      <ul>
        <% @bank.bank_subsidiaries.each do |subsidiary| %>
        <li><%= link_to subsidiary, subsidiary %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No hay sucursales</p>
    <% end %>

    <%= link_to 'Edit this bank', edit_bank_path(@bank), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this bank', bank_path(@bank), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to banks', banks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>